[package]
authors = ["Sébastien Crozet <developer@crozet.re>"]
name    = "kiss3d"
version = "0.32.0"

autoexamples = true
description  = "3D graphics engine for Rust."
edition      = "2018"
keywords     = ["3D", "graphics", "OpenGL", "KISS"]
license      = "BSD-3-Clause"
readme       = "README.md"
repository   = "https://github.com/sebcrozet/kiss3d"

include = [
    "src/**/*.rs",
    "src/**/*.frag",
    "src/**/*.vert",
    "src/text/*.ttf",
    "examples/**/*.rs",
    "examples/media",
    "examples/Cargo.toml",
    "Cargo.toml",
    "LICENSE",
    "Readme.md",
]


[lib]
name = "kiss3d"
path = "src/lib.rs"

[features]
conrod = ["conrod_core"]


[dependencies]
bitflags     = "1.3.2"
conrod_core  = { version = "0.76.0", features = ["wasm-bindgen"], optional = true }
either       = "1.6.1"
glow         = "0.11.0"
image        = "0.23.14"
instant      = { version = "0.1.12", features = ["wasm-bindgen"] }
libc         = "0.2.108"
nalgebra     = "0.29.0"
ncollide3d   = "0.32.0"
num-traits   = "0.2.14"
rusttype     = { version = "0.9.2", features = ["gpu_cache"] }
serde        = "1.0.130"
serde_derive = "1.0.130"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = "0.28.0"

# We repeat all three targets instead of any(target_arch = "wasm32", target_arch = "asmjs")
# to avoid https://github.com/koute/stdweb/issues/135
[target.wasm32-unknown-unknown.dependencies]
getrandom = { version = "0.2.3", features = ["js"] }
wasm-bindgen = "0.2.78"
web-sys = { version = "0.3.55", features = [
    "console",
    "KeyEvent",
    "KeyboardEvent",
    "MouseEvent",
    "WheelEvent",
    "Touch",
    "TouchEvent",
    "TouchList",
    "HtmlCanvasElement",
    "HtmlElement",
    "Window",
    "UiEvent",
    "Event",
    "EventTarget",
    "Element",
    "DomRect",
] }

[dev-dependencies]
nalgebra   = { version = "0.29.0", features = ["rand"] }
ncollide2d = "0.32.0"
rand       = "0.8.4"
